@token = 5b43970f468da7c3b2b8

POST http://localhost:8080/reservation
Authorization: {{token}}
Content-Type: application/json

{
    "user": "user1",
    "startDate": "startDate",
    "endDate":"endDate",
    "room": "someRoom"
}
###

GET http://localhost:8080/reservation/a70b6a5d3682f8529a2e
Authorization: {{token}}
###

GET http://localhost:8080/reservation/all
Authorization: {{token}}
###

PUT http://localhost:8080/reservation/a70b6a5d3682f8529a2e
Authorization: {{token}}
Content-Type: application/json

{
    "room": "someOtherRoom",
    "user": "user2"

}
###